### ISSUE TITLE
ReferenceError: Unknown plugin "babel-plugin-transform-class-properties"

### ISSUE THREAD

**Issue by paper520** [yelloxing/image2D#16]
**描述（describe）**
ERROR in ./src/main.jsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
ReferenceError: Unknown plugin "babel-plugin-transform-class-properties" specified in "C:\\Users\\32945\\Desktop\\image2D\\docs\\.babelrc" at 0, attempted to resolve relative to "C:\\Users\\32945\\Desktop\\image2D\\docs"
    at C:\Users\32945\Desktop\image2D\docs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (C:\Users\32945\Desktop\image2D\docs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:158:20)
    at OptionManager.mergeOptions (C:\Users\32945\Desktop\image2D\docs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:234:36)
    at OptionManager.init (C:\Users\32945\Desktop\image2D\docs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (C:\Users\32945\Desktop\image2D\docs\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (C:\Users\32945\Desktop\image2D\docs\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (C:\Users\32945\Desktop\image2D\docs\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (C:\Users\32945\Desktop\image2D\docs\node_modules\babel-loader\lib\index.js:50:20)
    at Object.module.exports (C:\Users\32945\Desktop\image2D\docs\node_modules\babel-loader\lib\index.js:173:20)
 @ multi ./src/main.jsx main[0]

**如何重现（How to Reproduce）**
```shell
cd docs
npm run dev
```

**预期（Expect）**
你本来的期望结果（Your expected results？）？

**截屏（Screenshots）**
如果有必须，可以截屏描述（If necessary, you can capture the description.）。

**问题设备或浏览器，可以添加多个（Problem device or browser, you can add more than one）：**
 - 设备名称（Name of device）: ASUS
 - 操作系统（operating system）: windows 10
 - 浏览器（Browser）: [eg：chrome43]

**补充（supplement）**
更多说明在这里添加（More instructions are added here.）。

**Comment by yelloxing** [comment]
karmal测试已经被qunit代替
